trigger:
- main  # or 'master'

pool:
  name: Default
  demands:
    - agent.name -equals CJTAgent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13'
  displayName: 'Set up Python 3.13'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest
  displayName: 'Run tests'