trigger:
- main  # or 'master' if you're using that

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.3'
  displayName: 'Set up Python 3.13.3'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest  # or `python -m unittest discover`
  displayName: 'Run tests'